### ISSUE TITLE
Can it run on vs2015？When I runned it in vs2015,I founded  the position of target box no change.

### ISSUE THREAD

**Issue by Clitost** [3fffff/BACF#2]

**Comment by 3fffff** [comment]
correct the error

**Comment by 3fffff** [comment]
now all works

**Comment by Clitost** [comment]
Many thanks,it works well.Your version is much faster than the matlab version.I found the   matlab version of bacf  use the HOG feature。But I don't know if the HOG feature is also used in your code.

**Comment by 3fffff** [comment]
used raw pixels in function BACF::compute_feature_vec
patch.convertTo(feature_data, CV_32FC1, 1.0 / 255.0, -0.5);

**Comment by Clitost** [comment]
Thanks
